<?php

namespace Database\Seeders;

use App\Models\item;
use App\Models\categories;
use App\Models\Unit;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Elektronik
            [
                'sku' => 'ELEC001',
                'name' => 'Smartphone Samsung A53',
                'category_id' => 1,
                'unit_id' => 1,
                'stock' => 15,
                'stock_min' => 5,
                'price' => 3500000.00,
                'description' => 'Smartphone Samsung Galaxy A53 5G dengan display AMOLED 6.1 inch, RAM 8GB, Storage 256GB. Kondisi seperti baru.',
                'condition' => 'Seperti Baru',
                'image' => 'products/smartphone-samsung.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'ELEC002',
                'name' => 'Laptop HP Pavilion 15',
                'category_id' => 1,
                'unit_id' => 1,
                'stock' => 8,
                'stock_min' => 2,
                'price' => 7500000.00,
                'description' => 'Laptop HP Pavilion 15 dengan Prosesor Intel i7 Gen 11, RAM 16GB, SSD 512GB. Layar FHD 15.6 inch. Kondisi seperti baru.',
                'condition' => 'Seperti Baru',
                'image' => 'products/laptop-hp.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'ELEC003',
                'name' => 'Headphone Wireless Sony',
                'category_id' => 1,
                'unit_id' => 1,
                'stock' => 25,
                'stock_min' => 10,
                'price' => 1200000.00,
                'description' => 'Headphone nirkabel Sony dengan noise cancellation, battery 30 jam, sound quality premium.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/headphone-sony.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'ELEC004',
                'name' => 'Tablet iPad Air 4',
                'category_id' => 1,
                'unit_id' => 1,
                'stock' => 10,
                'stock_min' => 3,
                'price' => 6500000.00,
                'description' => 'iPad Air 4 dengan layar Liquid Retina 10.9 inch, chip A14 Bionic, storage 256GB. Display seperti baru.',
                'condition' => 'Seperti Baru',
                'image' => 'products/ipad-air.jpg',
                'is_active' => true,
            ],

            // Fashion & Pakaian
            [
                'sku' => 'FASH001',
                'name' => 'Kemeja Casual Levi\'s Original',
                'category_id' => 2,
                'unit_id' => 1,
                'stock' => 40,
                'stock_min' => 15,
                'price' => 350000.00,
                'description' => 'Kemeja casual Levi\'s original, warna biru navy, size M. Material 100% cotton, nyaman dipakai sehari-hari.',
                'condition' => 'Seperti Baru',
                'image' => 'products/kemeja-levis.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'FASH002',
                'name' => 'Jaket Denim Vintage',
                'category_id' => 2,
                'unit_id' => 1,
                'stock' => 20,
                'stock_min' => 5,
                'price' => 450000.00,
                'description' => 'Jaket denim vintage klasik, warna biru tua, fit regular, bahan tebal dan berkualitas.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/jaket-denim.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'FASH003',
                'name' => 'T-Shirt Band The Beatles',
                'category_id' => 2,
                'unit_id' => 1,
                'stock' => 35,
                'stock_min' => 10,
                'price' => 120000.00,
                'description' => 'T-shirt band The Beatles vintage, design klasik, bahan cotton berkualitas tinggi.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/tshirt-beatles.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'FASH004',
                'name' => 'Celana Jeans Skinny Zara',
                'category_id' => 2,
                'unit_id' => 1,
                'stock' => 30,
                'stock_min' => 8,
                'price' => 320000.00,
                'description' => 'Celana jeans skinny dari Zara, warna hitam, size 30, bahan stretchy dan nyaman.',
                'condition' => 'Seperti Baru',
                'image' => 'products/celana-jeans-zara.jpg',
                'is_active' => true,
            ],

            // Sepatu
            [
                'sku' => 'SHOE001',
                'name' => 'Sneaker Nike Air Force 1',
                'category_id' => 3,
                'unit_id' => 1,
                'stock' => 18,
                'stock_min' => 5,
                'price' => 850000.00,
                'description' => 'Sneaker Nike Air Force 1 original, warna putih, size 42, kondisi masih bagus.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/sneaker-nike.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'SHOE002',
                'name' => 'Sepatu Formal Clarks',
                'category_id' => 3,
                'unit_id' => 1,
                'stock' => 12,
                'stock_min' => 3,
                'price' => 680000.00,
                'description' => 'Sepatu formal pria dari Clarks, warna coklat, size 41, bahan kulit asli yang nyaman dipakai lama.',
                'condition' => 'Seperti Baru',
                'image' => 'products/sepatu-formal-clarks.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'SHOE003',
                'name' => 'Sandal Adidas Slides',
                'category_id' => 3,
                'unit_id' => 1,
                'stock' => 50,
                'stock_min' => 20,
                'price' => 180000.00,
                'description' => 'Sandal Adidas slides original, warna hitam, size 42, nyaman untuk santai.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/sandal-adidas.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'SHOE004',
                'name' => 'Sepatu Boots Timberland',
                'category_id' => 3,
                'unit_id' => 1,
                'stock' => 8,
                'stock_min' => 2,
                'price' => 1200000.00,
                'description' => 'Sepatu boots Timberland 6 inch, warna tan, size 41, bahan kulit premium tahan lama.',
                'condition' => 'Seperti Baru',
                'image' => 'products/boots-timberland.jpg',
                'is_active' => true,
            ],

            // Tas & Dompet
            [
                'sku' => 'BAG001',
                'name' => 'Backpack Duffel Bag',
                'category_id' => 4,
                'unit_id' => 1,
                'stock' => 22,
                'stock_min' => 8,
                'price' => 280000.00,
                'description' => 'Backpack duffel bag kapasitas besar 40L, warna abu-abu, material waterproof, cocok untuk traveling.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/backpack-duffel.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'BAG002',
                'name' => 'Tas Kantor Leather Briefcase',
                'category_id' => 4,
                'unit_id' => 1,
                'stock' => 14,
                'stock_min' => 4,
                'price' => 520000.00,
                'description' => 'Tas kantor leather briefcase, warna coklat, bahan kulit asli berkualitas, elegan dan profesional.',
                'condition' => 'Seperti Baru',
                'image' => 'products/briefcase-leather.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'BAG003',
                'name' => 'Dompet Panjang Hermes',
                'category_id' => 4,
                'unit_id' => 1,
                'stock' => 18,
                'stock_min' => 6,
                'price' => 420000.00,
                'description' => 'Dompet panjang model Hermes, warna merah, material kulit berkualitas tinggi, desain elegan.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/dompet-hermes.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'BAG004',
                'name' => 'Tas Tangan Branded Coach',
                'category_id' => 4,
                'unit_id' => 1,
                'stock' => 10,
                'stock_min' => 3,
                'price' => 890000.00,
                'description' => 'Tas tangan branded Coach authentic, warna cream, bahan canvas premium, masih mulus seperti baru.',
                'condition' => 'Seperti Baru',
                'image' => 'products/handbag-coach.jpg',
                'is_active' => true,
            ],

            // Aksesori
            [
                'sku' => 'ACC001',
                'name' => 'Jam Tangan Digital G-Shock',
                'category_id' => 5,
                'unit_id' => 1,
                'stock' => 28,
                'stock_min' => 10,
                'price' => 850000.00,
                'description' => 'Jam tangan digital G-Shock original, warna hitam, water resistant 200m, tahan banting.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/gshock-watch.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'ACC002',
                'name' => 'Gelang Kulit Braided',
                'category_id' => 5,
                'unit_id' => 1,
                'stock' => 45,
                'stock_min' => 15,
                'price' => 120000.00,
                'description' => 'Gelang kulit anyam (braided), warna coklat, desain elegan cocok untuk pria dan wanita.',
                'condition' => 'Baru',
                'image' => 'products/bracelet-leather.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'ACC003',
                'name' => 'Sunglasses Ray-Ban',
                'category_id' => 5,
                'unit_id' => 1,
                'stock' => 20,
                'stock_min' => 8,
                'price' => 680000.00,
                'description' => 'Kacamata Ray-Ban original Aviator, lensa hitam, frame metal, UV protection 100%.',
                'condition' => 'Seperti Baru',
                'image' => 'products/rayban-sunglasses.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'ACC004',
                'name' => 'Kalung Rantai Perak',
                'category_id' => 5,
                'unit_id' => 1,
                'stock' => 32,
                'stock_min' => 12,
                'price' => 280000.00,
                'description' => 'Kalung rantai perak 925, panjang 50cm, desain minimalis elegan, cocok untuk casual dan formal.',
                'condition' => 'Baru',
                'image' => 'products/necklace-silver.jpg',
                'is_active' => true,
            ],

            // Furnitur
            [
                'sku' => 'FURN001',
                'name' => 'Meja Makan Kayu Jati',
                'category_id' => 6,
                'unit_id' => 1,
                'stock' => 5,
                'stock_min' => 1,
                'price' => 2800000.00,
                'description' => 'Meja makan 6 kursi dari kayu jati solid, ukuran 180x90cm, finishing berkualitas tinggi.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/dining-table-jati.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'FURN002',
                'name' => 'Sofa L-Shape Minimalis',
                'category_id' => 6,
                'unit_id' => 1,
                'stock' => 3,
                'stock_min' => 1,
                'price' => 4200000.00,
                'description' => 'Sofa L-Shape minimalis modern, warna abu-abu, kain berkualitas, nyaman dan stylish.',
                'condition' => 'Seperti Baru',
                'image' => 'products/sofa-lshape.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'FURN003',
                'name' => 'Lemari Pajangan Kaca',
                'category_id' => 6,
                'unit_id' => 1,
                'stock' => 8,
                'stock_min' => 2,
                'price' => 1500000.00,
                'description' => 'Lemari pajangan dengan pintu kaca, tinggi 180cm, material MDF berkualitas, desain modern.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/cabinet-glass.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'FURN004',
                'name' => 'Ranjang Kayu Minimalis',
                'category_id' => 6,
                'unit_id' => 1,
                'stock' => 6,
                'stock_min' => 2,
                'price' => 1800000.00,
                'description' => 'Ranjang kayu minimalis ukuran queen size 160x200cm, material solid, design elegan.',
                'condition' => 'Seperti Baru',
                'image' => 'products/bed-wooden.jpg',
                'is_active' => true,
            ],

            // Rumah Tangga
            [
                'sku' => 'HOME001',
                'name' => 'Blender Philips',
                'category_id' => 7,
                'unit_id' => 1,
                'stock' => 16,
                'stock_min' => 5,
                'price' => 650000.00,
                'description' => 'Blender Philips 2 liter, motor 750W, 3 speed, gelas kaca berkualitas tinggi.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/blender-philips.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'HOME002',
                'name' => 'Microwave Panasonic',
                'category_id' => 7,
                'unit_id' => 1,
                'stock' => 10,
                'stock_min' => 3,
                'price' => 1200000.00,
                'description' => 'Microwave Panasonic 25L, 1000W, sensor teknologi modern, mudah digunakan.',
                'condition' => 'Seperti Baru',
                'image' => 'products/microwave-panasonic.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'HOME003',
                'name' => 'Setrika Uap Teflon',
                'category_id' => 7,
                'unit_id' => 1,
                'stock' => 25,
                'stock_min' => 10,
                'price' => 280000.00,
                'description' => 'Setrika uap dengan alas teflon, 2200W, semprot air otomatis, hemat energi.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/iron-steam.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'HOME004',
                'name' => 'Vacuum Cleaner Suction',
                'category_id' => 7,
                'unit_id' => 1,
                'stock' => 12,
                'stock_min' => 3,
                'price' => 1800000.00,
                'description' => 'Vacuum cleaner dengan suction kuat 2500Pa, kapasitas tangki 2.5L, filter HEPA, cocok untuk lantai dan karpet.',
                'condition' => 'Seperti Baru',
                'image' => 'products/vacuum-cleaner.jpg',
                'is_active' => true,
            ],

            // Olahraga
            [
                'sku' => 'SPORT001',
                'name' => 'Sepeda MTB 27 Speed',
                'category_id' => 8,
                'unit_id' => 1,
                'stock' => 7,
                'stock_min' => 2,
                'price' => 2500000.00,
                'description' => 'Sepeda gunung (MTB) 27 speed, frame aluminium, ban 26 inch, rem disk, siap off-road.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/bike-mtb.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'SPORT002',
                'name' => 'Yoga Mat Premium',
                'category_id' => 8,
                'unit_id' => 1,
                'stock' => 35,
                'stock_min' => 15,
                'price' => 320000.00,
                'description' => 'Yoga mat premium anti-slip, tebal 8mm, warna ungu, material TPE eco-friendly.',
                'condition' => 'Baru',
                'image' => 'products/yoga-mat.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'SPORT003',
                'name' => 'Dumbbel Set 20kg',
                'category_id' => 8,
                'unit_id' => 6,
                'stock' => 12,
                'stock_min' => 3,
                'price' => 580000.00,
                'description' => 'Set dumbbel 20kg (2x10kg), coating neoprene, handle ergonomis, cocok untuk home gym.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/dumbbell-set.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'SPORT004',
                'name' => 'Raket Tennis Wilson',
                'category_id' => 8,
                'unit_id' => 1,
                'stock' => 9,
                'stock_min' => 2,
                'price' => 1200000.00,
                'description' => 'Raket tennis Wilson Blade series, frame graphite composite, grip comfort, unstring.',
                'condition' => 'Seperti Baru',
                'image' => 'products/tennis-racket.jpg',
                'is_active' => true,
            ],

            // Buku & Media
            [
                'sku' => 'BOOK001',
                'name' => 'Novel Laskar Pelangi',
                'category_id' => 9,
                'unit_id' => 1,
                'stock' => 20,
                'stock_min' => 5,
                'price' => 85000.00,
                'description' => 'Novel Laskar Pelangi karya Andrea Hirata, cetakan baru, kondisi seperti baru, bacaan wajib.',
                'condition' => 'Seperti Baru',
                'image' => 'products/book-laskar.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'BOOK002',
                'name' => 'Komik One Piece Vol 100',
                'category_id' => 9,
                'unit_id' => 1,
                'stock' => 15,
                'stock_min' => 5,
                'price' => 65000.00,
                'description' => 'Komik One Piece volume 100, kondisi bagus, koleksi lengkap, warna cerah.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/comic-onepiece.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'BOOK003',
                'name' => 'DVD Movie Avatar 2',
                'category_id' => 9,
                'unit_id' => 1,
                'stock' => 10,
                'stock_min' => 3,
                'price' => 150000.00,
                'description' => 'DVD Film Avatar 2 (The Way of Water) original, kualitas HD, original packaging.',
                'condition' => 'Seperti Baru',
                'image' => 'products/dvd-avatar.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'BOOK004',
                'name' => 'Buku Masak Indonesia Lezat',
                'category_id' => 9,
                'unit_id' => 1,
                'stock' => 18,
                'stock_min' => 6,
                'price' => 95000.00,
                'description' => 'Buku resep masakan Indonesia, banyak gambar, bahan mudah ditemukan, step-by-step.',
                'condition' => 'Bekas - Bagus',
                'image' => 'products/cookbook-indo.jpg',
                'is_active' => true,
            ],

            // Mainan & Game
            [
                'sku' => 'GAME001',
                'name' => 'Rubik\'s Cube 3x3',
                'category_id' => 10,
                'unit_id' => 1,
                'stock' => 50,
                'stock_min' => 20,
                'price' => 75000.00,
                'description' => 'Rubik cube 3x3 original, smooth turning, warna cerah, cocok untuk pemula hingga profesional.',
                'condition' => 'Baru',
                'image' => 'products/rubiks-cube.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'GAME002',
                'name' => 'PS5 Game FIFA 24',
                'category_id' => 10,
                'unit_id' => 1,
                'stock' => 8,
                'stock_min' => 2,
                'price' => 450000.00,
                'description' => 'Game FIFA 24 untuk PlayStation 5, original sealed, english version.',
                'condition' => 'Baru',
                'image' => 'products/game-fifa24.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'GAME003',
                'name' => 'Board Game Catan',
                'category_id' => 10,
                'unit_id' => 1,
                'stock' => 12,
                'stock_min' => 4,
                'price' => 320000.00,
                'description' => 'Board game Catan (Settlers of Catan), untuk 3-4 pemain, durasi 60 menit, fun game.',
                'condition' => 'Seperti Baru',
                'image' => 'products/board-game-catan.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'GAME004',
                'name' => 'Action Figure One Piece',
                'category_id' => 10,
                'unit_id' => 1,
                'stock' => 25,
                'stock_min' => 8,
                'price' => 180000.00,
                'description' => 'Action figure One Piece Luffy Gear 5, tinggi 15cm, detail bagus, cocok untuk koleksi.',
                'condition' => 'Baru',
                'image' => 'products/figure-onepiece.jpg',
                'is_active' => true,
            ],

            // Kecantikan & Perawatan
            [
                'sku' => 'BEAUTY001',
                'name' => 'Skincare Set La Roche Posay',
                'category_id' => 11,
                'unit_id' => 1,
                'stock' => 30,
                'stock_min' => 10,
                'price' => 520000.00,
                'description' => 'Set skincare La Roche Posay (cleanser, toner, moisturizer), untuk kulit sensitif, original.',
                'condition' => 'Baru',
                'image' => 'products/skincare-laroche.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'BEAUTY002',
                'name' => 'Lipstick MAC Ruby Woo',
                'category_id' => 11,
                'unit_id' => 1,
                'stock' => 20,
                'stock_min' => 5,
                'price' => 280000.00,
                'description' => 'Lipstick MAC Ruby Woo, warna merah klasik, long lasting, finishing matte, iconic color.',
                'condition' => 'Baru',
                'image' => 'products/lipstick-mac.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'BEAUTY003',
                'name' => 'Hair Serum Argan Oil',
                'category_id' => 11,
                'unit_id' => 4,
                'stock' => 40,
                'stock_min' => 15,
                'price' => 185000.00,
                'description' => 'Hair serum argan oil murni, 100ml, non-greasy, membuat rambut shiny dan lembut.',
                'condition' => 'Baru',
                'image' => 'products/serum-argan.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'BEAUTY004',
                'name' => 'Perfume Dior Sauvage',
                'category_id' => 11,
                'unit_id' => 4,
                'stock' => 15,
                'stock_min' => 5,
                'price' => 950000.00,
                'description' => 'Parfum Dior Sauvage 100ml original, aroma fresh dan elegant, tahan lama, pria dan unisex.',
                'condition' => 'Baru',
                'image' => 'products/perfume-sauvage.jpg',
                'is_active' => true,
            ],

            // Makanan & Minuman
            [
                'sku' => 'FOOD001',
                'name' => 'Kopi Specialty Grade Arabika',
                'category_id' => 12,
                'unit_id' => 3,
                'stock' => 100,
                'stock_min' => 30,
                'price' => 120000.00,
                'description' => 'Kopi specialty arabika biji pilihan, dari Sumatera, 500g, medium roast, aroma kuat.',
                'condition' => 'Baru',
                'image' => 'products/coffee-arabika.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'FOOD002',
                'name' => 'Teh Hijau Premium Jasmine',
                'category_id' => 12,
                'unit_id' => 3,
                'stock' => 80,
                'stock_min' => 25,
                'price' => 95000.00,
                'description' => 'Teh hijau premium dengan jasmine, 250g, wangi alami, 1 paket untuk 50 teh.',
                'condition' => 'Baru',
                'image' => 'products/tea-jasmine.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'FOOD003',
                'name' => 'Coklat Artisanal Dark 70%',
                'category_id' => 12,
                'unit_id' => 3,
                'stock' => 60,
                'stock_min' => 20,
                'price' => 85000.00,
                'description' => 'Coklat artisanal dark chocolate 70% cocoa, 200g, dari cokelat craft lokal, premium.',
                'condition' => 'Baru',
                'image' => 'products/chocolate-dark.jpg',
                'is_active' => true,
            ],
            [
                'sku' => 'FOOD004',
                'name' => 'Madu Raw Organic Flores',
                'category_id' => 12,
                'unit_id' => 4,
                'stock' => 45,
                'stock_min' => 15,
                'price' => 180000.00,
                'description' => 'Madu raw organic dari Flores, 500ml, tidak dipanaskan, murni 100%, nutrisi lengkap.',
                'condition' => 'Baru',
                'image' => 'products/honey-flores.jpg',
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            item::create($product);
        }
    }
}
